Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2019-06, with the labels that each got.

#27 allow Julia 1.2
  .travis.yml
  Project.toml
Labels: compat, travis

#31 Feature/templatedsolverparams
  src/NeedsAHome.jl
  src/services/GraphsDFG.jl
  test/interfaceTests.jl
Labels: solver params

#37 ls getVarIds now search tags too
  src/Common.jl
  src/DistributedFactorGraphs.jl
  src/services/GraphsDFG.jl
Labels: enhancement

#41 CloudGraphsDFG implementation
  .travis.yml
  Project.toml
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/GraphsDFG.jl
  src/GraphsDFG/entities/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/entities/AbstractTypes.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/entities/DistributedFactorGraph.jl
  src/services/AbstractDFG.jl
  src/services/DFGVariable.jl
  src/services/LightDFGraph.jl
  test/REQUIRE
  test/cloudGraphsDFGTests.jl
  test/interfaceTests.jl
  test/runtests.jl
Labels: api, breaking change, database, serialization

#47 Updating README
  README.md
Labels: documentation

#48 ls() and lsf() return symbols rather than full variables/factors
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  test/cloudGraphsDFGTests.jl
  test/interfaceTests.jl
  test/runtests.jl
Labels: api, breaking change, enhancement
