Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2019-10, with the labels that each got.

#127 bugfix cloud sparse adj matrix
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
Labels: bug fix, cloudgraphs

#125 draw graph circles squares
  src/GraphsDFG/services/GraphsDFG.jl
  src/entities/DFGVariable.jl
  test/interfaceTests.jl
Labels: enhancement

#154 General variable+factor packing and unpacking functions for DFG
  docs/src/variable_factor_serialization.md
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
Labels: api, serialization

#150 Towards #149 - Slightly improved without breaking changes.
  src/entities/DFGVariable.jl
Labels: enhancement

#138 Removing MetaGraphsDFG and SymbolDFG exports, adding test
  src/DFGPlots/DFGPlots.jl
  src/DistributedFactorGraphs.jl
  src/LightDFG/services/LightDFG.jl
  src/MetaGraphsDFG/MetaGraphsDFG.jl
  src/SymbolDFG/SymbolDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  test/runtests.jl
Labels: drivers, obsolete

#160 Adding module back in for SymbolDFG
  src/DistributedFactorGraphs.jl
  src/SymbolDFG/SymbolDFG.jl
Labels: bug

#163 Trying IIFTest without direct dependency
  .travis.yml
  Project.toml
  test/obsolete_nowinRoME/cloudGraphsDFGTests.jl
  test/runtests.jl
Labels: testing

#140 [WIP] GraphsDFG and LightGraphsDFG implementation of user/robot/session data
  src/GraphsDFG/entities/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/entities/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/services/AbstractDFG.jl
  test/interfaceTests.jl
Labels: api, enhancement

#170 Fixing CGDFG and 0.5 cleanup
  Project.toml
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CGStructure.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/MetaGraphsDFG/MetaGraphsDFG.jl
  src/MetaGraphsDFG/services/MetaGraphsDFG.jl
  src/SymbolDFG/SymbolDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  src/services/AbstractDFG.jl
  src/services/CompareUtils.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  test/LightDFGSummaryTypes.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/runtests.jl
  test/sandbox.jl
Labels: breaking change, cloudgraphs

#176 add upper bounds to Project.toml
  Project.toml
Labels: compat, toml

#173 Backport of the CGDFG code and unit tests
  .travis.yml
  Project.toml
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CGStructure.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/Common.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/MetaGraphsDFG/services/MetaGraphsDFG.jl
  src/SymbolDFG/SymbolDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/DFGVariable.jl
  test/LightDFGSummaryTypes.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/runtests.jl
Labels: backport

#179 Fixed versions for release
  Project.toml
Labels: bug

#180 allow fast finish on travis testing EDIT: also travis update and documenter cleanup
  .travis.yml
  docs/Project.toml
  docs/make.jl
Labels: travis

#183 Closes #147 PointParametricEst implementation
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGVariable.jl
  src/services/DFGVariable.jl
  test/LightDFGSummaryTypes.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
Labels: PPE, api, breaking change

#171 FileDFG testing
  src/FileDFG/services/FileDFG.jl
  test/fileDFGTests.jl
  test/obsolete_nowinRoME/FileDFG.jl
  test/runtests.jl
  test/sandbox.jl
Labels: FileDFG, testing
