Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2019-11, with the labels that each got.

#187 Additional functionality for graph sentinels
  Project.toml
  README.md
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CGStructure.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  test/CGStructureTests.jl
  test/iifInterfaceTests.jl
  test/runtests.jl
  test/sandbox.jl
Labels: cloudgraphs

#181 CGDFG Sentinel Structure
  Project.toml
  README.md
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/entities/CGStructure.jl
  src/CloudGraphsDFG/services/CGStructure.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  test/CGStructureTests.jl
  test/iifInterfaceTests.jl
  test/runtests.jl
  test/sandbox.jl
Labels: cloudgraphs

#188 add Symbol*String
  src/Common.jl
Labels: enhancement

#189 Additional field in MeanMaxPPE
  src/entities/DFGVariable.jl
  test/LightDFGSummaryTypes.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
Labels: PPE

#184 Closes #149 DFGVariable softtype parametric type
  src/entities/DFGVariable.jl
  test/interfaceTests.jl
  test/runtests.jl
Labels: breaking change, performance

#190 add missing export of AbstractPointParametricEst
  src/DistributedFactorGraphs.jl
Labels: api

#191 Removing prefixes for compare
  src/services/CompareUtils.jl
Labels: bug fix

#193 Adding factor data compare to DFG
  src/DistributedFactorGraphs.jl
  src/services/DFGFactor.jl
Labels: enhancement

#203 better vnd constructor
  src/entities/DFGVariable.jl
Labels: api, enhancement, maintenance

#197 Update DFGVariable.jl
  src/entities/DFGVariable.jl
Labels: enhancement

#198 add getSuggestedPPE
  src/DistributedFactorGraphs.jl
  src/entities/DFGVariable.jl
  test/interfaceTests.jl
Labels: api, enhancement

#209 adding solvable for tree work
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/SymbolDFG/SymbolDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  src/services/AbstractDFG.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/runtests.jl
Labels: enhancement

#212 Filtering getSubgraphAroundNode with solvable field
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  src/services/AbstractDFG.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
Labels: enhancement

#210 Feature - 4Q19 - v0.51 cleanup
  Project.toml
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/DFGPlots/DFGPlots.jl
  src/DistributedFactorGraphs.jl
  src/SymbolDFG/services/SymbolDFG.jl
  src/attic/MetaGraphsDFG/DFGPlots.jl
  src/attic/MetaGraphsDFG/MetaGraphsDFG.jl
  src/attic/MetaGraphsDFG/entities/MetaGraphsDFG.jl
  src/attic/MetaGraphsDFG/services/MetaGraphsDFG.jl
  src/entities/DFGVariable.jl
  src/services/DFGVariable.jl
  test/interfaceTests.jl
  test/plottingTest.jl
  test/runtests.jl
Labels: maintenance

#216 Updated CGDFG, still slow, but working. Stoked to refactor soon
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/services/AbstractDFG.jl
  test/iifInterfaceTests.jl
  test/runtests.jl
Labels: cloudgraphs

#217 Moving isSolveInProgress to solver structures
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  test/attic/HexagonalCloud.jl
  test/attic/HexagonalLightGraphs.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/obsolete_nowinRoME/cloudGraphsDFGTests.jl
Labels: breaking change

#219 Release 0.5.1
  Project.toml
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/DFGPlots/DFGPlots.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/SymbolDFG/SymbolDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  src/attic/MetaGraphsDFG/DFGPlots.jl
  src/attic/MetaGraphsDFG/MetaGraphsDFG.jl
  src/attic/MetaGraphsDFG/entities/MetaGraphsDFG.jl
  src/attic/MetaGraphsDFG/services/MetaGraphsDFG.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  test/LightDFGSummaryTypes.jl
  test/attic/HexagonalCloud.jl
  test/attic/HexagonalLightGraphs.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/obsolete_nowinRoME/cloudGraphsDFGTests.jl
  test/plottingTest.jl
  test/runtests.jl
Labels: release

#223 isVariable and isFactor
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/SymbolDFG/SymbolDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  src/services/AbstractDFG.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
Labels: bug fix

#224 tab = 4 spaces
  src/CloudGraphsDFG/services/CGStructure.jl
  src/Common.jl
  src/DFGPlots/DFGPlots.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  src/attic/MetaGraphsDFG/services/MetaGraphsDFG.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
Labels: maintenance

#225 add setSolvable!
  src/DistributedFactorGraphs.jl
  src/services/AbstractDFG.jl
  test/interfaceTests.jl
Labels: enhancement

#227 Missing accessor methods for DFGVariable and DFGFactor
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  test/interfaceTests.jl
  test/runtests.jl
Labels: refactor
