Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2019-07, with the labels that each got.

#57 starting migration of IIF low level functions to DFG, and fixes
  src/Common.jl
  src/DistributedFactorGraphs.jl
  src/NeedsAHome.jl
  src/entities/DFGFactor.jl
Labels: bug fix, downstream

#61 CloudGraphs rewritten for DFG is now working
  Project.toml
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/entities/DFGFactor.jl
  test/HexagonalCloud.jl
Labels: cloudgraphs

#63 partialinit bool becomes inferdim float
  src/entities/DFGVariable.jl
  src/services/DFGVariable.jl
Labels: breaking change, types

#69 Patch for FileDFG issue
  src/FileDFG/services/FileDFG.jl
Labels: serialization
