Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2019-12, with the labels that each got.

#228 In-memory and File-based Bigdata stores
  .gitignore
  src/BigData.jl
  src/BigData/BigData.jl
  src/BigData/entities/AbstractBigDataEntries.jl
  src/BigData/entities/AbstractDataStore.jl
  src/BigData/entities/FileDataStore.jl
  src/BigData/entities/InMemoryDataStore.jl
  src/BigData/services/AbstractBigDataEntries.jl
  src/BigData/services/AbstractDataStore.jl
  src/BigData/services/FileDataStore.jl
  src/BigData/services/InMemoryDataStore.jl
  src/DFGPlots/DFGPlots.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/services/AbstractDFG.jl
  src/services/CompareUtils.jl
  src/services/DFGVariable.jl
  test/DataStoreTests.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/runtests.jl
Labels: bigdata

#230 add timestamps to DFGFactor/Summary and closest functions
  src/Common.jl
  src/CommonAccessors.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/DFGFactor.jl
  test/LightDFGSummaryTypes.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
Labels: api, breaking change, testing, types, user experience

#242 table of badges for readme
  README.md
Labels: documentation

#244 Small refactor to unblock 0.5.2
  test/CGStructureTests.jl
  test/runtests.jl
  test/solveTest.jl
Labels: testing

#243 buildSubgraphFromLabels! function in needsahome.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/entities/GraphsDFG.jl
  src/needsahome.jl
  test/needsahomeTests.jl
  test/runtests.jl
Labels: api, downstream

#245 bump version to v0.5.2
  Project.toml
Labels: toml

#238 Release 0.5.2 RC1
  .gitignore
  Project.toml
  README.md
  src/BigData.jl
  src/BigData/BigData.jl
  src/BigData/entities/AbstractBigDataEntries.jl
  src/BigData/entities/AbstractDataStore.jl
  src/BigData/entities/FileDataStore.jl
  src/BigData/entities/InMemoryDataStore.jl
  src/BigData/services/AbstractBigDataEntries.jl
  src/BigData/services/AbstractDataStore.jl
  src/BigData/services/FileDataStore.jl
  src/BigData/services/InMemoryDataStore.jl
  src/CloudGraphsDFG/services/CGStructure.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Common.jl
  src/CommonAccessors.jl
  src/DFGPlots/DFGPlots.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/GraphsDFG/entities/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/SymbolDFG/SymbolDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  src/attic/MetaGraphsDFG/services/MetaGraphsDFG.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/needsahome.jl
  src/services/AbstractDFG.jl
  src/services/CompareUtils.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  test/CGStructureTests.jl
  test/DataStoreTests.jl
  test/LightDFGSummaryTypes.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/needsahomeTests.jl
  test/runtests.jl
  test/solveTest.jl
Labels: release

#247 bug fix, remove DFG.
  src/needsahome.jl
Labels: bug fix

#248 Consolidate, drop buildSubFG_SPECIAL
  src/needsahome.jl
Labels: maintenance, refactor
