Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2019-09, with the labels that each got.

#88 Integrating @affie's changes into master (v0.4 release)
  .gitignore
  Project.toml
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Common.jl
  src/DFGPlots/DFGPlots.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/entities/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/FactorGraphs/BiMaps.jl
  src/LightDFG/FactorGraphs/FactorGraphs.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/entities/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/MetaGraphsDFG/MetaGraphsDFG.jl
  src/MetaGraphsDFG/entities/MetaGraphsDFG.jl
  src/MetaGraphsDFG/services/MetaGraphsDFG.jl
  src/SymbolDFG/SymbolDFG.jl
  src/SymbolDFG/SymbolFactorGraphs/SymbolFactorGraphs.jl
  src/SymbolDFG/SymbolFactorGraphs/symboledge.jl
  src/SymbolDFG/entities/SymbolDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  src/services/AbstractDFG.jl
  test/interfaceTests.jl
  test/runtests.jl
Labels: api, breaking change

#99 improve readability slightly
  src/FileDFG/services/FileDFG.jl
Labels: style

#98 travis for julia 1.3
  .travis.yml
Labels: travis

#104 Removing DataFrame references
  Project.toml
  docs/src/func_ref.md
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/MetaGraphsDFG/MetaGraphsDFG.jl
  test/FileDFG.jl
  test/interfaceTests.jl
  test/runtests.jl
Labels: obsolete

#113 more ls for types
  src/Common.jl
Labels: api, enhancement

#112 FEATURE backport lsWho, lsfWho
  src/Common.jl
Labels: backport, enhancement

#109 some code cleanup, more dispatch possible
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Common.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/entities/LightDFG.jl
  src/services/AbstractDFG.jl
  test/interfaceTests.jl
  test/obsolete_nowinRoME/FileDFG.jl
  test/obsolete_nowinRoME/HexagonalCloud.jl
  test/obsolete_nowinRoME/HexagonalLightGraphs.jl
  test/obsolete_nowinRoME/cloudGraphsDFGTests.jl
  test/runtests.jl
Labels: maintenance

#122 Clearer depreciation error in Symbol and Light DFG
  src/LightDFG/entities/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/MetaGraphsDFG/entities/MetaGraphsDFG.jl
  src/MetaGraphsDFG/services/MetaGraphsDFG.jl
  src/SymbolDFG/entities/SymbolDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  test/interfaceTests.jl
Labels: light graphs, user experience

#116 alias for sort dfg symbol lists
  Project.toml
  docs/src/func_ref.md
  src/Common.jl
  src/DFGPlots/DFGPlots.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  test/interfaceTests.jl
  test/plottingTest.jl
  test/runtests.jl
Labels: api, user experience
