Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2019-08, with the labels that each got.

#68 Option with removed nodeCounter and labelDict
  .travis.yml
  Project.toml
  src/LightGraphsDFG/entities/LightGraphsDFG.jl
  src/LightGraphsDFG/services/LightGraphsDFG.jl
Labels: api, enhancement, light graphs, refactor

#70 add codecov badge
  .travis.yml
  README.md
Labels: bug fix

#71 try/catches around serialization
  src/FileDFG/services/FileDFG.jl
Labels: enhancement, serialization

#67 LightGraphs integration
  .travis.yml
  Project.toml
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightGraphsDFG/LightGraphsDFG.jl
  src/LightGraphsDFG/entities/LightGraphsDFG.jl
  src/LightGraphsDFG/services/LightGraphsDFG.jl
  test/HexagonalLightGraphs.jl
  test/interfaceTests.jl
  test/runtests.jl
Labels: drivers

#82 Hotfix/backendset
  src/LightGraphsDFG/services/LightGraphsDFG.jl
  test/interfaceTests.jl
Labels: bug fix, light graphs, testing

#80 Add GraphPlot.jl plots Issue #78
  src/DFGPlots/DFGPlots.jl
  src/DistributedFactorGraphs.jl
Labels: visualization

#83 add features from IIF
  src/NeedsAHome.jl
Labels: downstream, enhancement, refactor

#79 Sparse Int Adjacency matrix
  src/LightGraphsDFG/LightGraphsDFG.jl
  src/LightGraphsDFG/services/LightGraphsDFG.jl
Labels: enhancement, light graphs, performance

#86 getAdjacencyMatrixSparse integration
  Project.toml
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/LightGraphsDFG/services/LightGraphsDFG.jl
  src/SymbolDFG/SymbolDFG.jl
  src/SymbolDFG/entities/SymbolDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  src/services/interfaces.jl
  test/interfaceTests.jl
Labels: enhancement, performance
