Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2020-10, with the labels that each got.

#670 convertStructType for ::UnionAll too
  src/Common.jl
Labels: enhancement, serialization

#672 deserialize vartype{T} fix #671
  Project.toml
  src/services/Serialization.jl
Labels: VariableType, bug fix, enhancement, serialization

#673 v0.10.6-rc1
  Project.toml
  src/Common.jl
  src/DistributedFactorGraphs.jl
  src/services/Serialization.jl
Labels: release

#679 Use dispatch for isPrior to allow overloading
  src/services/DFGFactor.jl
  test/testBlocks.jl
Labels: enhancement

#680 getXxxPPE --> getPPEXxx
  Project.toml
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/services/DFGVariable.jl
  test/testBlocks.jl
Labels: API, PPE, deprecation, enhancement

#681 v0.10.7 rc1
  Project.toml
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  test/testBlocks.jl
Labels: release

#683 Update DFGVariable.jl
  src/services/DFGVariable.jl
Labels: bug fix, supersolve

#684 v0.10.8 rc1
  src/services/DFGVariable.jl
Labels: release

#686 improve serialization eval
  src/services/Serialization.jl
Labels: enhancement, serialization
