Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2020-09, with the labels that each got.

#655 Release v0.10.3 RC1
  Project.toml
  README.md
  src/services/Serialization.jl
Labels: release

#660 restore PackedType convert functions
  Project.toml
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/Common.jl
  src/DistributedFactorGraphs.jl
  src/services/Serialization.jl
Labels: API, downstream, refactor, serialization

#661 v0.10.4-rc1
  Project.toml
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/Common.jl
  src/DistributedFactorGraphs.jl
  src/services/Serialization.jl
Labels: release

#663 breaking change, AbstractRelative
  Project.toml
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
Labels: breaking change, deprecation, refactor, types

#664 v0.10.5-rc1
  Project.toml
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
Labels: release

#666 better deprecation warning
  src/DistributedFactorGraphs.jl
Labels: deprecation, maintenance
