Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2020-04, with the labels that each got.

#373 Refactor graph copy and subgraph functions
  attic/sandbox.jl
  src/DFGPlots/DFGPlots.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/entities/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/needsahome.jl
  src/services/AbstractDFG.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: api, maintenance, refactor

#376 copyGraph separate variables factors
  .travis.yml
  Project.toml
  src/DFGPlots/DFGPlots.jl
  src/LightDFG/services/LightDFG.jl
  src/services/AbstractDFG.jl
  test/testBlocks.jl
Labels: standardization

#377 0.7.3-rc1
  .travis.yml
  Project.toml
  attic/sandbox.jl
  src/DFGPlots/DFGPlots.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/entities/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/needsahome.jl
  src/services/AbstractDFG.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: release

#380 Feature ls2 close #332
  src/DistributedFactorGraphs.jl
  src/services/AbstractDFG.jl
  test/testBlocks.jl
Labels: user experience

#382 v0.7.4-rc1
  Project.toml
  src/DistributedFactorGraphs.jl
  src/services/AbstractDFG.jl
  test/testBlocks.jl
Labels: release

#381 Restore arm tests
  .travis.yml
Labels: testing

#384 Update readme with correct neo4j version
  README.md
Labels: documentation

#387 CloudGraphsDFG User Robot Session data consolidate
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  test/CGStructureTests.jl
  test/consolInterfaceDev.jl
  test/iifInterfaceTests.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: cloudgraphs, maintenance, standardization

#390 CGDFG and GraphsDFG fix for #375 and `factor.data` usage
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/Deprecated.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/services/Serialization.jl
  test/testBlocks.jl
Labels: bug fix, cloudgraphs, standardization

#385 Change GraphsDFG to module
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/services/AbstractDFG.jl
  test/iifInterfaceTests.jl
Labels: maintenance

#393 FIX CGDFG addFactor! errors but adds factor
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  test/consolInterfaceDev.jl
  test/runtests.jl
  test/testBlocks.jl
  test/testFurther.jl
Labels: bug fix, cloudgraphs

#386 Fixing cloud solving functions
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/services/AbstractDFG.jl
  test/runtests.jl
Labels: cloudgraphs, downstream, maintenance

#396 Cloud Tags SET Functions and tests
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  test/consolInterfaceDev.jl
Labels: cloudgraphs, maintenance

#399 add verbose option
  src/services/DFGVariable.jl
Labels: enhancement

#402 add hasDataEntry, rm ReturnTypes
  src/BigData/services/AbstractBigDataEntries.jl
  src/DistributedFactorGraphs.jl
Labels: enhancement

#405 addDataEntry!,
  src/BigData/services/AbstractBigDataEntries.jl
  src/DistributedFactorGraphs.jl
Labels: api, enhancement, feature request

#408 typo
  src/BigData/services/AbstractBigDataEntries.jl
Labels: bug fix

#407 v0.7.5-rc1
  .travis.yml
  Project.toml
  README.md
  src/BigData/services/AbstractBigDataEntries.jl
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/services/AbstractDFG.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/CGStructureTests.jl
  test/consolInterfaceDev.jl
  test/iifInterfaceTests.jl
  test/runtests.jl
  test/testBlocks.jl
  test/testFurther.jl
Labels: release

#412 Standardize and test cloud graph variable and factor crud
  .travis.yml
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/entities/DFGFactor.jl
  src/services/Serialization.jl
  test/consolInterfaceDev.jl
  test/interfaceTests.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: cloudgraphs, crud, testing

#410 add datastore (oops)
  src/BigData/services/AbstractBigDataEntries.jl
Labels: bug fix

#413 Update cgdfg test and fixing bugs
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  test/consolInterfaceDev.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: bug fix, cloudgraphs, standardization

#416 Update cgdfg tests and small bugfixes
  src/services/AbstractDFG.jl
  test/consolInterfaceDev.jl
  test/testBlocks.jl
Labels: cloudgraphs, standardization, testing, user experience

#418 Update .travis.yml to only build on certain pushed branches
  .travis.yml
Labels: testing, travis

#420 force remove
  src/FileDFG/services/FileDFG.jl
Labels: bug fix
