Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2020-02, with the labels that each got.

#272 Interface tests pass except for a few compares and renamed to BiadjacencyMatrix
  src/BigData/BigData.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Common.jl
  src/CommonAccessors.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/entities/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/entities/AbstractDFGSummary.jl
  src/entities/SkeletonDFGFactor.jl
  src/entities/SkeletonDFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/CompareUtils.jl
  src/services/DFGVariable.jl
  test/DataStoreTests.jl
  test/LightDFGSummaryTypes.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/runtests.jl
Labels: maintenance, standardization, testing

#278 Refactor comparison funcitons
  src/Deprecated.jl
  src/services/CompareUtils.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  test/compareTests.jl
  test/fileDFGTests.jl
  test/iifCompareTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/runtests.jl
Labels: design, standardization, testing

#251 add printVariable (wip)
  src/DistributedFactorGraphs.jl
  src/needsahome.jl
  src/services/AbstractDFG.jl
Labels: enhancement, help wanted, user experience

#284 Cleanup on packing and unpacking
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CGStructure.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/services/AbstractDFG.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
Labels: cloudgraphs

#289 getSofttype fix and no keyword arg on solverkey as standard
  src/Common.jl
  src/Deprecated.jl
  src/services/AbstractDFG.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  test/iifInterfaceTests.jl
  test/testBlocks.jl
Labels: bug fix, maintenance, standardization

#294 Fix for travis maximum log exceeded in iif
  src/services/CompareUtils.jl
Labels: bug fix

#295 sortDFG wrapper close #186 and close #241
  src/Common.jl
  src/Deprecated.jl
  test/testBlocks.jl
Labels: bug fix, sorting

#297 Start deprecate on field fncargvID #288
  src/CommonAccessors.jl
  src/entities/DFGFactor.jl
Labels: deprecation, maintenance

#301 Maintenance Cleanup for v0.6
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Common.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/entities/AbstractDFGSummary.jl
  src/services/AbstractDFG.jl
  src/services/DFGVariable.jl
  test/LightDFGSummaryTypes.jl
  test/iifInterfaceTests.jl
  test/testBlocks.jl
Labels: maintenance

#303 update broken and missing docstrings
  docs/Project.toml
  docs/make.jl
  docs/src/BuildingGraphs.md
  docs/src/GraphData.md
  docs/src/TraversingAndQuerying.md
  docs/src/func_ref.md
  src/LightDFG/FactorGraphs/FactorGraphs.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/DFGVariable.jl
Labels: documentation

#285 Efficient calls for PPEs (and general transaction pattern) for CGDFG
  Project.toml
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CGStructure.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/DistributedFactorGraphs.jl
  src/LightDFG/entities/LightDFG.jl
  src/services/AbstractDFG.jl
  src/services/Serialization.jl
Labels: cloudgraphs

#307 Fixing tar file saving, comparator for Graphs.jl, and the FileDFG tests
  src/FileDFG/services/FileDFG.jl
  src/services/CompareUtils.jl
  test/fileDFGTests.jl
Labels: FileDFG, bug fix, enhancement, user experience

#314 fix docstring and index.md install instructions
  README.md
  docs/src/index.md
  src/services/AbstractDFG.jl
Labels: documentation

#317 try add julia 1.4 testing
  .travis.yml
Labels: julia version, testing, travis

#322 [feature] setTimestamp!(dfg, lbl, ts)
  src/needsahome.jl
  src/services/CommonAccessors.jl
  src/services/DFGVariable.jl
  test/testBlocks.jl
Labels: api, feature request

#321 update and add api image
  docs/extra/CoreAPI.fods
  docs/src/imgs/CoreAPI.png
  docs/src/ref_api.md
Labels: documentation

#324 remove v0.6 deprecations
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/services/DFGFactor.jl
  test/iifInterfaceTests.jl
  test/testBlocks.jl
Labels: deprecation, maintenance

#326 re-add keyword in saveDFG with deprecation
  src/FileDFG/services/FileDFG.jl
Labels: api, bug fix, deprecation

#327 set IIF test branch back to "upstream/dfg_integration_test"
  test/runtests.jl
Labels: testing

#334 optional GraphPlot in deps,
  Project.toml
Labels: maintenance, toml, visualization

#335 v0.6.1-rc1
  Project.toml
Labels: release

#337 Copy into graph changed variable order
  attic/sandbox.jl
  src/LightDFG/services/LightDFG.jl
  src/services/AbstractDFG.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: bug fix, urgent

#340 v0.6.2-rc2
  Project.toml
Labels: release
