Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2020-12, with the labels that each got.

#700 softtype -> variableType
  Project.toml
  docs/extra/CoreAPI.fods
  docs/src/GraphData.md
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/entities/DFGVariable.jl
  src/services/CompareUtils.jl
  src/services/CustomPrinting.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/LightDFGSummaryTypes.jl
  test/compareTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: VariableType, deprecation, maintenance, standardization

#714 isPathFactorsHomogeneous, better path
  Project.toml
  src/DistributedFactorGraphs.jl
  src/LightDFG/services/LightDFG.jl
  src/services/AbstractDFG.jl
Labels: enhancement

#717 add filters for shortest path
  src/LightDFG/services/LightDFG.jl
  src/entities/DFGFactor.jl
  src/services/AbstractDFG.jl
Labels: enhancement, light graphs, needs testing

#718 Fixing listVariable and listFactor with regex
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
Labels: bug fix, cloudgraphs, needs testing

#719 xtra filter or shortest path, initialized
  src/LightDFG/services/LightDFG.jl
  src/services/DFGVariable.jl
Labels: downstream, enhancement

#720 v0.11.2-rc1
  Project.toml
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/DistributedFactorGraphs.jl
  src/LightDFG/services/LightDFG.jl
  src/entities/DFGFactor.jl
  src/services/AbstractDFG.jl
  src/services/DFGVariable.jl
Labels: release

#722 rm excess printout
  src/LightDFG/services/LightDFG.jl
Labels: maintenance
