Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2020-06, with the labels that each got.

#491 Refactor docs structure for maintainability and v0.8
  docs/extra/CoreAPI.fods
  docs/make.jl
  docs/src/BuildingGraphs.md
  docs/src/DataStructure.md
  docs/src/DrawingGraphs.md
  docs/src/GraphData.md
  docs/src/TraversingAndQuerying.md
  docs/src/apis/graphs.md
  docs/src/func_ref.md
  docs/src/getting_started.md
  docs/src/imgs/CoreAPI.png
  docs/src/index.md
  docs/src/ref_api.md
  docs/src/variable_factor_serialization.md
  docs/src/variables_and_factors.md
  src/DFGPlots/DFGPlots.jl
  src/DistributedFactorGraphs.jl
  src/services/AbstractDFG.jl
Labels: documentation, refactor, standardization

#495 help with #494 cases
  src/Deprecated.jl
  src/FileDFG/services/FileDFG.jl
Labels: api, deprecation

#496 check file exists on loadDFG
  src/FileDFG/services/FileDFG.jl
Labels: FileDFG, enhancement, user experience

#497 improve DFGFactor show
  src/entities/DFGFactor.jl
  src/services/CustomPrinting.jl
  test/iifInterfaceTests.jl
Labels: testing, user experience, visualization

#498 assert loadDFG, listSupersolve
  src/DistributedFactorGraphs.jl
  src/services/AbstractDFG.jl
  test/fileDFGTests.jl
  test/testBlocks.jl
Labels: FileDFG, api, enhancement, supersolve, testing

#499 simplify jl 1.4
  .travis.yml
Labels: testing, travis

#501 consolidate printFactor, bugfix
  src/services/CustomPrinting.jl
  test/fileDFGTests.jl
  test/interfaceTests.jl
Labels: bug fix, enhancement, testing, visualization

#503 deepcopySupersolve!
  src/DistributedFactorGraphs.jl
  src/services/DFGVariable.jl
Labels: api, enhancement, needs testing, supersolve

#504 enhance printFactor
  src/services/CustomPrinting.jl
Labels: enhancement, visualization

#505 Update CGDFG
  LICENSE
  src/CloudGraphsDFG/LICENSE
Labels: maintenance
