Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2020-08, with the labels that each got.

#571 Deprecate softtype fields, add getManifolds and getDimension interface
  src/Deprecated.jl
  src/entities/DFGVariable.jl
  src/services/CompareUtils.jl
Labels: deprecation, maintenance, softtype

#572 softtype warn once
  src/Deprecated.jl
Labels: deprecation, maintenance

#576 Small Data Types and in-memory CRUD
  attic/InMemoryDataStore.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: crud, enhancement, smalldata

#584 Make directory if it doesn't exist with @info
  src/DataBlobs/services/BlobStores.jl
  src/DataBlobs/services/FileDataEntryBlob.jl
  test/consol_DataEntryBlobTests.jl
Labels: data: entry=>blob, enhancement, user experience

#583 Macro to create a new <:InferenceVariable
  src/DistributedFactorGraphs.jl
  src/entities/DFGVariable.jl
  src/services/DFGVariable.jl
  test/consol_DataEntryBlobTests.jl
  test/testBlocks.jl
Labels: enhancement, softtype, user experience

#588 Fix for non-millisecond timestamps
  src/services/Serialization.jl
  test/testBlocks.jl
Labels: bug fix

#585 CGDFG blobs as nodes
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/DataBlobs/services/BlobStores.jl
  src/DataBlobs/services/InMemoryDataEntryBlob.jl
  src/DistributedFactorGraphs.jl
  src/services/AbstractDFG.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: cloudgraphs

#592 Deleting v0.10 deprecations
  src/Deprecated.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/DFGFactor.jl
  test/testBlocks.jl
Labels: deprecation, maintenance, standardization

#597 Split DistributedFactorGraphs.BlobStoreEntry
  src/services/Serialization.jl
Labels: bug fix, data: entry=>blob, serialization

#602 solverKey -> solveKey, fix #599
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/Deprecated.jl
  src/entities/DFGVariable.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/testBlocks.jl
Labels: maintenance, standardization, types

#604 allow both saveDFG argument orders,
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  test/fileDFGTests.jl
Labels: API, FileDFG, enhancement, feature request, standardization, testing

#591 Robust ZonedTimestamp fixer
  src/services/Serialization.jl
Labels: littlebitofvoodoomagic

#607 export addVariable
  src/DistributedFactorGraphs.jl
Labels: API, VariableType, types

#606 shorter loadDFG temp folder name
  src/FileDFG/services/FileDFG.jl
Labels: FileDFG

#609 proper deprecation listSolvekeys,
  src/Deprecated.jl
Labels: API, bug fix, deprecation

#605 Save/load softtype with module
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/services/Serialization.jl
Labels: VariableType, enhancement, serialization

#613 Fix docs and cleanup deprecated
  attic/DataStoreTests.jl
  docs/src/func_ref.md
  src/DataBlobs/DataBlobs.jl
  src/DataBlobs/services/AbstractDataEntries.jl
  src/DataBlobs/services/DataEntryBlob.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  test/runtests.jl
Labels: deprecation, documentation, maintenance

#614 change updateVariableSolverData message
  src/services/DFGVariable.jl
Labels: deprecation, maintenance

#611 Update Project.toml - Bump DFG version to v0.10.0
  Project.toml
Labels: toml

#593 add InMemoryBlobStore, more tests, and small bugfixes
  attic/InMemoryDataStore.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/DataBlobs/services/BlobStores.jl
  test/consol_DataEntryBlobTests.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: data: entry=>blob, enhancement

#610 add filters for listSolveKeys
  src/services/AbstractDFG.jl
  test/runtests.jl
Labels: API, enhancement

#620 Put back some deprecated for a bit longer and backward compat for loadDFG
  src/Deprecated.jl
  src/services/Serialization.jl
Labels: VariableType, deprecation, maintenance

#601 DFG version in serialized data
  Project.toml
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CGStructure.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/DistributedFactorGraphs.jl
  src/services/Serialization.jl
Labels: cloudgraphs

#627 .dims deprecation message `getDimension`
  src/Deprecated.jl
Labels: VariableType, bug fix

#629 addVariable! labels->tags
  Project.toml
  docs/src/BuildingGraphs.md
  docs/src/DrawingGraphs.md
  docs/src/GraphData.md
  src/FileDFG/services/FileDFG.jl
  test/CGStructureTests.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/solveTest.jl
  test/testFurther.jl
Labels: deprecation, maintenance, standardization

#633 Update .travis.yml
  .travis.yml
Labels: bug fix, travis

#634 Update readme and skip IIF on tags
  .travis.yml
  README.md
Labels: documentation, travis

#636 List all methods for data CRUD in docs
  src/DataBlobs/services/DataEntryBlob.jl
Labels: documentation

#642 Allow documenting struct in @defVariable
  src/services/DFGVariable.jl
Labels: VariableType, bug fix, documentation

#644 Update tests for IIF#862
  test/fileDFGTests.jl
  test/interfaceTests.jl
Labels: bug fix, downstream, testing

#645 Regex filter for solve keys in listSolveKeys
  src/services/AbstractDFG.jl
  test/testBlocks.jl
Labels: feature request, supersolve

#648 Add warn_if_absent to update verbs
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Deprecated.jl
  src/LightDFG/services/LightDFG.jl
  src/services/DFGVariable.jl
Labels: API, crud, maintenance, standardization

#646 v0.10.2-rc1
  Project.toml
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Deprecated.jl
  src/LightDFG/services/LightDFG.jl
  src/services/AbstractDFG.jl
  src/services/DFGVariable.jl
  test/fileDFGTests.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: WORK OUTSTANDING, release
