Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2020-05, with the labels that each got.

#423 Test more todot orders
  test/testBlocks.jl
Labels: testing

#417 CG Structure updates and creating sentinel nodes in the constructor
  src/CloudGraphsDFG/entities/CGStructure.jl
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CGStructure.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
Labels: cloudgraphs

#428 SKIP_CGDFG_TESTS env var
  .travis.yml
  test/runtests.jl
Labels: testing

#429 put back CGDFG solve test
  test/runtests.jl
Labels: cloudgraphs, testing

#422 step to rename FactorOperationalMemory
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
  src/services/CompareUtils.jl
  test/testBlocks.jl
Labels: maintenance

#427 Rename hasOrphans and isFullyConnected to isConnected
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/services/AbstractDFG.jl
  test/iifInterfaceTests.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: refactor, standardization

#430 fetchData and docs
  src/BigData/services/AbstractBigDataEntries.jl
  src/DistributedFactorGraphs.jl
Labels: bigdata, database, enhancement, user experience

#431 v0.7.6-rc1
  .travis.yml
  Project.toml
  src/BigData/services/AbstractBigDataEntries.jl
  src/CloudGraphsDFG/entities/CGStructure.jl
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CGStructure.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/GraphsDFG/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/entities/DFGFactor.jl
  src/services/AbstractDFG.jl
  src/services/CompareUtils.jl
  src/services/Serialization.jl
  test/consolInterfaceDev.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: release

#371 Remove orphaned factors on deleteVariable!
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/services/AbstractDFG.jl
  test/LightDFGSummaryTypes.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: api, breaking change

#421 Validation during creation of DFG drivers
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CGStructure.jl
  src/Common.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/GraphsDFG.jl
  src/GraphsDFG/entities/GraphsDFG.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/entities/LightDFG.jl
  test/consolInterfaceDev.jl
  test/testBlocks.jl
Labels: cloudgraphs, enhancement

#433 decodePackedType with solverParams type, part of #425
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/services/AbstractDFG.jl
  src/services/CompareUtils.jl
  src/services/Serialization.jl
  test/consolInterfaceDev.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: FIX ME, regression, serialization, standardization, testing

#442 convenience buildSubgraph, fix #441
  src/Deprecated.jl
  src/FileDFG/services/FileDFG.jl
  src/services/AbstractDFG.jl
  src/services/CompareUtils.jl
  test/consolInterfaceDev.jl
  test/testBlocks.jl
Labels: enhancement, user experience

#443 fix #439
  src/entities/DFGFactor.jl
Labels: enhancement, performance, types

#444 Run full test with IIF_TEST
  .travis.yml
Labels: testing, travis

#440 Remove deprecated fncargvID and remove unused frommodule.
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
  src/services/CompareUtils.jl
  src/services/Serialization.jl
  test/DataStoreTests.jl
  test/compareTests.jl
  test/interfaceTests.jl
  test/needsahomeTests.jl
  test/plottingTest.jl
  test/testBlocks.jl
Labels: maintenance, refactor

#447 Move GraphsDFG to attic and remove tests
  attic/GraphsDFG/GraphsDFG.jl
  attic/GraphsDFG/entities/GraphsDFG.jl
  attic/GraphsDFG/services/GraphsDFG.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  test/CGStructureTests.jl
  test/IIF4DoorsTests.jl
  test/iifInterfaceTests.jl
  test/needsahomeTests.jl
  test/plottingTest.jl
  test/runtests.jl
  test/testBlocks.jl
  test/testFurther.jl
Labels: GraphsDFG, deprecation, maintenance

#449 Also dispach on solverData type for rebuildFactorMetadata!
  attic/GraphsDFG/entities/GraphsDFG.jl
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/LightDFG/entities/LightDFG.jl
  src/entities/AbstractDFG.jl
  src/services/AbstractDFG.jl
  src/services/Serialization.jl
  test/CGStructureTests.jl
  test/IIF4DoorsTests.jl
  test/consolInterfaceDev.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/runtests.jl
  test/testBlocks.jl
  test/testFurther.jl
Labels: maintenance, serialization

#450 Remove _internalId
  src/Deprecated.jl
  src/LightDFG/services/LightDFG.jl
  src/entities/AbstractDFG.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/CommonAccessors.jl
  src/services/CompareUtils.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/LightDFGSummaryTypes.jl
  test/iifInterfaceTests.jl
  test/testBlocks.jl
Labels: deprecation, maintenance

#452 leave full buildSubgraphFromLabels! in deprecated, as its not compatable
  src/Deprecated.jl
Labels: bug fix, deprecation

#457 missing export
  src/Deprecated.jl
Labels: api, deprecation

#455 buildSubgraphFromLabels!: rather error with notes of replacement functions
  src/Deprecated.jl
Labels: bug fix, deprecation

#454 Custom pretty-printing #448
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/needsahome.jl
  src/services/CustomPrinting.jl
  test/interfaceTests.jl
Labels: api, user experience

#459 buildSubgraph fix and testing
  src/DistributedFactorGraphs.jl
  src/services/AbstractDFG.jl
  test/testBlocks.jl
Labels: api, bug fix, standardization

#463 validate variable order on updateFactor!
  src/LightDFG/services/LightDFG.jl
  test/testBlocks.jl
Labels: LightDFG, bug fix, maintenance

#466 Remove DFGNodeParams and make DFGFactor immutable
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/entities/AbstractDFG.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/CommonAccessors.jl
  src/services/CompareUtils.jl
  src/services/CustomPrinting.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/DataStoreTests.jl
  test/interfaceTests.jl
  test/plottingTest.jl
  test/testBlocks.jl
Labels: maintenance, performance, standardization

#467 Remove get/setSerializationModule and always use Main
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/DistributedFactorGraphs.jl
  src/services/Serialization.jl
Labels: maintenance, serialization

#461 html DFG plotting on display
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/DFGPlots/DFGPlots.jl
  src/LightDFG/FactorGraphs/FactorGraphs.jl
Labels: visualization

#469 Remove excessive warnings for #462
  .travis.yml
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/services/Serialization.jl
Labels: backport

#471 Clean up testing and maintenance
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Common.jl
  src/DFGPlots/DFGPlots.jl
  src/DistributedFactorGraphs.jl
  src/services/AbstractDFG.jl
  test/CGStructureTests.jl
  test/LightDFGSummaryTypes.jl
  test/consolInterfaceDev.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/plottingTest.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: maintenance, standardization, testing

#476 add broadcasting
  src/FileDFG/services/FileDFG.jl
  src/services/AbstractDFG.jl
  test/testBlocks.jl
Labels: enhancement, standardization

#479 standardise to solverParams
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Deprecated.jl
  src/LightDFG/entities/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/services/DFGVariable.jl
  test/CGStructureTests.jl
  test/LightDFGSummaryTypes.jl
  test/iifInterfaceTests.jl
  test/needsahomeTests.jl
  test/runtests.jl
  test/testBlocks.jl
  test/testFurther.jl
Labels: maintenance, standardization

#478 Feature add nanosecond time to DFGVariable and DFGFactor
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: timing, types

#481 Mainly testing and maintenance
  src/CloudGraphsDFG/LICENSE
  src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
  src/Common.jl
  src/DFGPlots/DFGPlots.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/LightDFG/entities/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/CustomPrinting.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/LightDFGSummaryTypes.jl
  test/consolInterfaceDev.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/needsahomeTests.jl
  test/plottingTest.jl
  test/runtests.jl
  test/testBlocks.jl
  test/testFurther.jl
Labels: enhancement, maintenance, testing

#483 Update Deprecated.jl * Symbol
  src/Deprecated.jl
Labels: api, bug fix, downstream, regression, testing, travis

#484 move cgdfg to a module in dfg
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/Common.jl
  src/DistributedFactorGraphs.jl
  test/interfaceTests.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: cloudgraphs, maintenance

#486 getVariableLabelNumber, findFactorsBetweenNaive
  src/Common.jl
  src/DistributedFactorGraphs.jl
  src/services/AbstractDFG.jl
Labels: enhancement, feature request, needs documentation, needs testing

#489 Update .travis.yml
  .travis.yml
Labels: travis

#490 Don't make use of attic Deprecation of GraphsDFG but rather error
  attic/README.md
  src/Deprecated.jl
Labels: GraphsDFG, deprecation
