Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2020-07, with the labels that each got.

#522 Fixing CGDFG escaping issue #521
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
Labels: bug, cloudgraphs

#493 Docs examples
  docs/Project.toml
  docs/src/BuildingGraphs.md
  docs/src/DrawingGraphs.md
Labels: documentation, testing

#519 BigData rename
  src/BigData/BigData.jl
  src/BigData/entities/AbstractBigDataEntries.jl
  src/BigData/entities/InMemoryDataStore.jl
  src/BigData/services/AbstractBigDataEntries.jl
  src/BigData/services/AbstractDataStore.jl
  src/BigData/services/FileDataStore.jl
  src/BigData/services/InMemoryDataStore.jl
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/Common.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/entities/AbstractDFG.jl
  src/entities/DFGVariable.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/DataStoreTests.jl
  test/LightDFGSummaryTypes.jl
  test/consol_DataEntryBlobTests.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: data: entry=>blob, maintenance, standardization, testing

#529 Hotfix for lsf with tags filter and test
  src/LightDFG/services/LightDFG.jl
  test/testBlocks.jl
Labels: bug fix

#530 hotfix for lsf with tags filter and test close #528
  Project.toml
  src/LightDFG/services/LightDFG.jl
  test/testBlocks.jl
Labels: backport, bug fix, release

#526 Rename BigData files without code changes
  src/DataBlobs/DataBlobs.jl
  src/DataBlobs/entities/AbstractDataEntries.jl
  src/DataBlobs/entities/AbstractDataStore.jl
  src/DataBlobs/entities/FileDataStore.jl
  src/DataBlobs/entities/InMemoryDataStore.jl
  src/DataBlobs/services/AbstractDataEntries.jl
  src/DataBlobs/services/AbstractDataStore.jl
  src/DataBlobs/services/FileDataStore.jl
  src/DataBlobs/services/InMemoryDataStore.jl
  src/DistributedFactorGraphs.jl
Labels: data: entry=>blob

#537 Update as per #533
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
  src/services/DFGFactor.jl
  test/testBlocks.jl
Labels: api, deprecation, standardization, types

#536 add GFND.nullhypo::Float64
  Project.toml
  src/entities/DFGFactor.jl
  src/services/CompareUtils.jl
  test/testBlocks.jl
Labels: breaking change, downstream, enhancement, serialization, types

#538 cleanup for tagging
  docs/src/variable_factor_serialization.md
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
  src/services/AbstractDFG.jl
  test/testBlocks.jl
Labels: maintenance

#540 Use correct IIF branch
  test/runtests.jl
Labels: bug fix

#543 Change DateTime to ZonedDateTime
  Project.toml
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/CommonAccessors.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/LightDFGSummaryTypes.jl
  test/interfaceTests.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: enhancement

#545 Remove deprecated getInternalId test
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
Labels: bug fix, testing

#548 Update .travis.yml
  .travis.yml
  README.md
Labels: bug fix

#549 print nullhypo
  src/services/CustomPrinting.jl
Labels: enhancement

#517 CloudGraphs DFG Updates
  Project.toml
  src/CloudGraphsDFG/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CGStructure.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGVariable.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: cloudgraphs, enhancement

#556 update info printout cgdfg
  src/DistributedFactorGraphs.jl
Labels: cloudgraphs, maintenance

#550 DataEntry and BlobStore Options
  Project.toml
  src/DataBlobs/DataBlobs.jl
  src/DataBlobs/entities/AbstractDataEntries.jl
  src/DataBlobs/entities/AbstractDataStore.jl
  src/DataBlobs/entities/FileDataStore.jl
  src/DataBlobs/entities/InMemoryDataStore.jl
  src/DataBlobs/services/AbstractDataEntries.jl
  src/DataBlobs/services/AbstractDataStore.jl
  src/DataBlobs/services/BlobStores.jl
  src/DataBlobs/services/DataEntryBlob.jl
  src/DataBlobs/services/FileDataEntryBlob.jl
  src/DataBlobs/services/FileDataStore.jl
  src/DataBlobs/services/InMemoryDataEntryBlob.jl
  src/DataBlobs/services/InMemoryDataStore.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/LightDFG/entities/LightDFG.jl
  src/services/AbstractDFG.jl
  src/services/Serialization.jl
  test/consol_DataEntryBlobTests.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: api, breaking change, data: entry=>blob, standardization

#564 Remove params deprecation
  src/LightDFG/entities/LightDFG.jl
Labels: deprecation, maintenance

#562 Fix add- update- VariableSolverData and PPE deprecation
  src/Deprecated.jl
  src/services/DFGVariable.jl
Labels: bug fix

#566 bandaid on updateVariableSolverData!
  src/Deprecated.jl
  src/services/DFGVariable.jl
Labels: bug fix

#567 Precompile CGDFG based on ENV variable
  src/DistributedFactorGraphs.jl
Labels: bug fix, cloudgraphs

#569 Revert getSofttype to return in full
  src/services/DFGVariable.jl
Labels: bug fix, deprecation, regression
