Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2020-01, with the labels that each got.

#253 save and load to gzip as default
  src/FileDFG/services/FileDFG.jl
  test/fileDFGTests.jl
Labels: FileDFG, enhancement

#254 add getVariablePPE and deprecated
  src/DistributedFactorGraphs.jl
  src/LightDFG/entities/LightDFG.jl
  src/SymbolDFG/entities/SymbolDFG.jl
  src/attic/MetaGraphsDFG/entities/MetaGraphsDFG.jl
  src/entities/DFGVariable.jl
Labels: PPE, enhancement, maintenance

#255 fix fatal compilation errors
  src/entities/DFGVariable.jl
Labels: bug fix, compilation, maintenance

#256 dont change directory for save tar
  src/FileDFG/services/FileDFG.jl
Labels: FileDFG, enhancement

#258 estimateDict -> ppeDict and deprecation warns
  .travis.yml
  src/BigData/entities/AbstractBigDataEntries.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CommonAccessors.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/DFGVariable.jl
  test/LightDFGSummaryTypes.jl
  test/attic/HexagonalCloud.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
Labels: PPE, deprecation, testing, types

#259 v0.5.3-rc1
  .github/workflows/CompatHelper.yml
  .travis.yml
  Project.toml
  src/BigData/entities/AbstractBigDataEntries.jl
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/CommonAccessors.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/LightDFG/entities/LightDFG.jl
  src/SymbolDFG/entities/SymbolDFG.jl
  src/attic/MetaGraphsDFG/entities/MetaGraphsDFG.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/needsahome.jl
  src/services/AbstractDFG.jl
  src/services/DFGVariable.jl
  test/LightDFGSummaryTypes.jl
  test/attic/HexagonalCloud.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
Labels: release

#268 add solveCount to DFGVariable
  src/DistributedFactorGraphs.jl
  src/entities/DFGVariable.jl
  src/services/DFGVariable.jl
  test/interfaceTests.jl
Labels: enhancement, types

#267 tags as a set, idea for consideration
  src/Common.jl
  src/CommonAccessors.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  test/interfaceTests.jl
Labels: enhancement

#269 add unpack function for solvedCount
  src/DistributedFactorGraphs.jl
  src/entities/DFGVariable.jl
  src/services/DFGVariable.jl
  test/fileDFGTests.jl
  test/interfaceTests.jl
Labels: bug fix

#270 v0.5.4-rc1
  Project.toml
  src/DFGPlots/DFGPlots.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/entities/LightDFG.jl
  src/SymbolDFG/services/SymbolDFG.jl
  src/entities/DFGVariable.jl
  src/needsahome.jl
  src/services/AbstractDFG.jl
  src/services/DFGVariable.jl
  test/fileDFGTests.jl
  test/interfaceTests.jl
Labels: release

#275 delete temp folder from tar
  src/FileDFG/services/FileDFG.jl
Labels: FileDFG, enhancement
