Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2020-03, with the labels that each got.

#346 save multihypo,
  src/FileDFG/services/FileDFG.jl
  src/entities/DFGFactor.jl
Labels: FileDFG, bug fix, enhancement

#333 remove fncargID
  Project.toml
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/FileDFG/services/FileDFG.jl
  src/services/CompareUtils.jl
  src/services/Serialization.jl
  test/compareTests.jl
Labels: deprecation, maintenance

#347 better inner constructor
  src/entities/AbstractDFG.jl
  src/services/CommonAccessors.jl
Labels: enhancement

#310 Add event::Threads.Condition to VND
  .travis.yml
  Project.toml
  src/entities/DFGVariable.jl
Labels: DONT MERGE YET, enhancement, feature request, multithreading

#348 attempt fix for 279
  src/services/AbstractDFG.jl
Labels: bug fix, enhancement

#349 better printing api,
  src/DistributedFactorGraphs.jl
  src/needsahome.jl
Labels: api, enhancement

#350 remove some deprecations
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/needsahome.jl
  src/services/DFGVariable.jl
  test/testBlocks.jl
Labels: api, deprecation, maintenance, obsolete

#352 fix save load DFG issues 344
  Project.toml
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
Labels: FileDFG, bug fix

#354 Don't allow failures on IIF tests
  .travis.yml
Labels: bug fix, testing

#356 fix integration tests 354
  .travis.yml
  docs/src/GraphData.md
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/needsahome.jl
  src/services/DFGVariable.jl
  test/LightDFGSummaryTypes.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/testBlocks.jl
Labels: bug fix, testing

#361 v0.7.1-rc1
  .github/workflows/TagBot.yml
  .travis.yml
  docs/src/GraphData.md
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/needsahome.jl
  src/services/DFGVariable.jl
  test/LightDFGSummaryTypes.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/testBlocks.jl
Labels: release

#363 subgraph fnc comment
  src/needsahome.jl
Labels: maintenance, refactor

#368 update solver data by field and test
  src/services/DFGVariable.jl
  test/iifInterfaceTests.jl
  test/testBlocks.jl
Labels: api, downstream, enhancement, performance, standardization

#369 v0.7.2-rc1
  Project.toml
  README.md
  src/needsahome.jl
  src/services/DFGVariable.jl
  test/iifInterfaceTests.jl
  test/testBlocks.jl
Labels: release
