Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2021-06, with the labels that each got.

#777 v0.14.4-rc1
  Project.toml
  README.md
  src/services/CustomPrinting.jl
Labels: release

#779 is/set Marginalized, printVar, bump v0.14.5
  Project.toml
  src/DataBlobs/services/AbstractDataEntries.jl
  src/DistributedFactorGraphs.jl
  src/services/CustomPrinting.jl
  src/services/DFGVariable.jl
Labels: bug fix, enhancement

#780 v0.14.5-rc1
  Project.toml
  src/DataBlobs/services/AbstractDataEntries.jl
  src/DistributedFactorGraphs.jl
  src/services/CustomPrinting.jl
  src/services/DFGVariable.jl
Labels: release

#775 Cleanup defVariable and add getPointType
  src/DistributedFactorGraphs.jl
  src/services/DFGVariable.jl
  test/runtests.jl
  test/testBlocks.jl
  test/test_defVariable.jl
Labels: VariableType, breaking change, maintenance

#782 better factor printing
  src/services/CustomPrinting.jl
Labels: enhancement

#783 towards val::Vector{T}
  Project.toml
  src/DistributedFactorGraphs.jl
  src/entities/DFGVariable.jl
  src/services/CompareUtils.jl
  src/services/CustomPrinting.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/compareTests.jl
  test/plottingTest.jl
  test/testBlocks.jl
  test/test_defVariable.jl
Labels: breaking change, enhancement, standardization

#730 Converted travis to github ci
  .github/workflows/ci.yml
  README.md
  src/entities/DFGVariable.jl
  src/services/CustomPrinting.jl
  src/services/Serialization.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/runtests.jl
Labels: CI, standardization, testing

#786 fast-forward deprecation testing pre v0.15
  .github/workflows/ci.yml
  .travis.yml
  Project.toml
  README.md
  src/DataBlobs/services/AbstractDataEntries.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGVariable.jl
  src/services/CompareUtils.jl
  src/services/CustomPrinting.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/compareTests.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/plottingTest.jl
  test/runtests.jl
  test/testBlocks.jl
  test/test_defVariable.jl
Labels: deprecation, fast-foward, testing
