Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2021-01, with the labels that each got.

#723 general maintenance
  Project.toml
  src/LightDFG/services/LightDFG.jl
  src/entities/DFGFactor.jl
  test/iifCompareTests.jl
  test/testBlocks.jl
Labels: maintenance

#726 add AbstractFactor and AbstractPackedFactor
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
Labels: refactor, standardization, types

#731 Bugfixes for julia 1.6.0-beta1
  src/services/AbstractDFG.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: bug fix

#733 Fix isPathFactorsHomogeneous
  src/services/AbstractDFG.jl
Labels: bug fix

#734 findShortestPathDijkstra exists from to
  src/LightDFG/services/LightDFG.jl
Labels: bug fix

#735 fix todot test
  test/iifInterfaceTests.jl
Labels: bug fix, testing

#724 v0.11.3-rc1
  Project.toml
  src/DistributedFactorGraphs.jl
  src/LightDFG/services/LightDFG.jl
  src/entities/DFGFactor.jl
  src/services/AbstractDFG.jl
  test/iifCompareTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/testBlocks.jl
Labels: release

#736 drop Graphs.jl from compat
  Project.toml
Labels: GraphsDFG, compat, toml

#737 v0.11.3-rc2
  Project.toml
Labels: release
