Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2021-07, with the labels that each got.

#789 test getPointIdentity
  src/services/Serialization.jl
  test/test_defVariable.jl
Labels: API, testing

#790 slight improvement to serialization code
  src/services/Serialization.jl
Labels: enhancement, serialization

#792 Change to DefaultOrthogonalBasis and add as arg
  src/services/DFGVariable.jl
Labels: enhancement, manifolds
