Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2022-11, with the labels that each got.

#906 add mergeDataEntries!
  src/DataBlobs/services/AbstractDataEntries.jl
  src/DistributedFactorGraphs.jl
  test/consol_DataEntryBlobTests.jl
Labels: enhancement, testing, API, documentation, data: entry=>blob

#907 v0.18.7-rc1
  Project.toml
  src/DataBlobs/services/AbstractDataEntries.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/Neo4jDFG/services/Neo4jDFG.jl
  src/services/AbstractDFG.jl
  test/consol_DataEntryBlobTests.jl
Labels: release

#909 bug fix on mergeDataEntries
  src/DataBlobs/services/AbstractDataEntries.jl
Labels: bug fix

#910 kwarg to skip version checking on unpackVariable for performance
  src/services/Serialization.jl
Labels: performance, serialization

#911 enhancements for blob caching
  src/DataBlobs/services/BlobStores.jl
  src/DataBlobs/services/DataEntryBlob.jl
  src/DataBlobs/services/FileDataEntryBlob.jl
  src/GraphsDFG/entities/GraphsDFG.jl
  src/Neo4jDFG/services/CommonFunctions.jl
  src/services/AbstractDFG.jl
Labels: enhancement, data: entry=>blob, cache

#903 Better error message on getSolverData
  src/services/DFGVariable.jl
  test/testBlocks.jl
Labels: enhancement, testing

#914 rm extra variable, better type stability
  src/DataBlobs/services/BlobStores.jl
Labels: enhancement, performance

#916 make copyGraph faster
  src/services/AbstractDFG.jl
  src/services/Serialization.jl
Labels: enhancement

#917 incrDataLabelSuffix
  Project.toml
  src/DataBlobs/services/AbstractDataEntries.jl
  src/DistributedFactorGraphs.jl
  test/consol_DataEntryBlobTests.jl
  test/testBlocks.jl
Labels: enhancement, API, feature request
