Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2022-09, with the labels that each got.

#839 Optimizing the creation of a CGDFG.
  src/Neo4jDFG/entities/Neo4jDFG.jl
  src/Neo4jDFG/services/CGStructure.jl
  src/services/CustomPrinting.jl
  test/CGStructureTests.jl
  test/iifInterfaceTests.jl
  test/testBlocks.jl
Labels: enhancement

#900 blobs via uuids or labels
  Project.toml
  src/DataBlobs/services/AbstractDataEntries.jl
  src/DataBlobs/services/BlobStores.jl
  src/DataBlobs/services/DataEntryBlob.jl
  src/services/Serialization.jl
Labels: enhancement, data: entry=>blob

#901 release v0.18.6-rc1
  Project.toml
  src/DataBlobs/entities/AbstractDataEntries.jl
  src/DataBlobs/services/AbstractDataEntries.jl
  src/DataBlobs/services/BlobStores.jl
  src/DataBlobs/services/DataEntryBlob.jl
  src/DataBlobs/services/FileDataEntryBlob.jl
  src/DataBlobs/services/InMemoryDataEntryBlob.jl
  src/Neo4jDFG/entities/Neo4jDFG.jl
  src/Neo4jDFG/services/CGStructure.jl
  src/services/CustomPrinting.jl
  src/services/Serialization.jl
  test/CGStructureTests.jl
  test/iifInterfaceTests.jl
  test/testBlocks.jl
Labels: release
