Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2022-02, with the labels that each got.

#858 Changed error to use defined arg
  src/CloudGraphsDFG/services/CommonFunctions.jl
Labels: bug fix

#860 Forward port of fixes in DFG v0.17.1
  src/Neo4jDFG/services/CommonFunctions.jl
Labels: backport, fast-foward

#859 fix depr api
  src/services/CustomPrinting.jl
  src/services/Serialization.jl
  test/attic/HexagonalCloud.jl
Labels: maintenance, deprecation

#863 v0.18.1-rc1
  NEWS.md
  Project.toml
  README.md
  src/Neo4jDFG/services/CommonFunctions.jl
  src/services/CustomPrinting.jl
  src/services/Serialization.jl
  test/attic/HexagonalCloud.jl
Labels: release
