Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2022-01, with the labels that each got.

#826 New GraphsDFG, functional equivalent to LightDFG
  Project.toml
  attic/GraphsDFG/entities/GraphsDFG.jl
  attic/GraphsDFG/services/GraphsDFG.jl
  attic/README.md
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/FactorGraphs/BiMaps.jl
  src/GraphsDFG/FactorGraphs/FactorGraphs.jl
  src/GraphsDFG/GraphsDFG.jl
  src/GraphsDFG/entities/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: enhancement, compat, light graphs, deprecation, LightDFG, GraphsDFG

#827 refactor _packSolverData
  src/CloudGraphsDFG/services/CommonFunctions.jl
  src/services/Serialization.jl
Labels: serialization, refactor, maintenance, standardization

#832 switch to reconstFactorData
  src/DistributedFactorGraphs.jl
  src/services/Serialization.jl
  test/testBlocks.jl
Labels: enhancement, API, serialization, refactor, breaking change, downstream

#840 Update graph plot to GraphsDFG
  Project.toml
  src/DFGPlots/DFGPlots.jl
  test/runtests.jl
Labels: visualization, bug fix

#842 cleanup AbstractFactor and initAll!, more
  NEWS.md
  attic/DataStoreTests.jl
  src/Common.jl
  src/Deprecated.jl
  src/entities/DFGFactor.jl
  src/services/AbstractDFG.jl
  src/services/CompareUtils.jl
  test/attic/IIF4DoorsTests.jl
  test/iifCompareTests.jl
  test/testBlocks.jl
Labels: types, maintenance, deprecation

#843 update CI for JL 1.7
  .github/workflows/ci.yml
Labels: enhancement, testing, CI, upstream

#844 update deprecations
  NEWS.md
  attic/MetaGraphsDFG/DFGPlots.jl
  docs/src/DrawingGraphs.md
  src/CloudGraphsDFG/services/CloudGraphsDFG.jl
  src/DFGPlots/DFGPlots.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/services/AbstractDFG.jl
  src/services/DFGVariable.jl
  test/attic/IIF4DoorsTests.jl
  test/plottingTest.jl
  test/testBlocks.jl
Labels: enhancement, deprecation

#845 Neo4jDFG replaces CloudGraphsDFG
  LICENSE
  NEWS.md
  attic/DataStoreTests.jl
  attic/MetaGraphsDFG/services/MetaGraphsDFG.jl
  attic/SymbolDFG/services/SymbolDFG.jl
  docs/make.jl
  docs/src/BuildingGraphs.md
  docs/src/func_ref.md
  src/DistributedFactorGraphs.jl
  src/Neo4jDFG/LICENSE
  src/Neo4jDFG/Neo4jDFG.jl
  src/Neo4jDFG/entities/CGStructure.jl
  src/Neo4jDFG/entities/Neo4jDFG.jl
  src/Neo4jDFG/services/CGStructure.jl
  src/Neo4jDFG/services/CommonFunctions.jl
  src/Neo4jDFG/services/Neo4jDFG.jl
  src/services/AbstractDFG.jl
  test/CGStructureTests.jl
  test/attic/HexagonalCloud.jl
  test/attic/IIF4DoorsTests.jl
  test/consol_DataEntryBlobTests.jl
  test/fileDFGTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/runtests.jl
  test/testBlocks.jl
  test/testFurther.jl
Labels: types, cloudgraphs, maintenance, deprecation, possible breaking change

#849 Update ci.yml
  .github/workflows/ci.yml
Labels: CI, bug fix

#850 Update ci.yml
  .github/workflows/ci.yml
Labels: CI, bug fix, backport

#852 Fix documenter build/deploy
  docs/Project.toml
  docs/src/BuildingGraphs.md
  docs/src/DrawingGraphs.md
  docs/src/GraphData.md
  test/testFurther.jl
Labels: documentation, bug fix

#848 top level JSON2.write only, distr are JSON
  src/Neo4jDFG/services/Neo4jDFG.jl
  src/entities/DFGFactor.jl
  src/services/Serialization.jl
  test/testBlocks.jl
Labels: enhancement, serialization, breaking change, standardization

#855 Fix inferdim->infoPerCoord bug and Escalate inferdim depwarn to error
  src/Deprecated.jl
  src/entities/DFGVariable.jl
Labels: bug fix, deprecation
