Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2023-03, with the labels that each got.

#968 easier debugging downstream on json strings
  src/DataBlobs/DataBlobs.jl
  src/DataBlobs/services/AbstractBlobEntries.jl
  src/DataBlobs/services/Blob.jl
  src/DataBlobs/services/BlobEntry.jl
  src/DataBlobs/services/BlobStores.jl
  src/FileDFG/services/FileDFG.jl
Labels: enhancement, FileDFG

#973 fix unpackFactor on factorData, one use of JSON2
  Project.toml
  src/DistributedFactorGraphs.jl
  src/entities/DFGVariable.jl
  src/services/Serialization.jl
Labels: serialization, bug fix, dependencies

#974 limit version string warnings
  src/Deprecated.jl
Labels: enhancement, deprecation

#975 better to import JSON2 not using
  src/DistributedFactorGraphs.jl
Labels: enhancement, serialization, dependencies

#972 Restore IIF tests and some fixes
  .github/workflows/ci.yml
  src/Deprecated.jl
  src/services/CompareUtils.jl
  src/services/Serialization.jl
  test/data/0_20_0.tar.gz
  test/data/archive/0_12_0.tar.gz
  test/fileDFGTests.jl
  test/iifCompareTests.jl
  test/iifInterfaceTests.jl
Labels: testing, bug fix

#977 Drop JSON2 dependancy
  Project.toml
  docs/src/variable_factor_serialization.md
  src/DistributedFactorGraphs.jl
  src/services/Serialization.jl
  test/runtests.jl
Labels: serialization, maintenance

#983 Sorting out blob and data naming
  .github/workflows/ci.yml
  NEWS.md
  Project.toml
  attic/DataBlobs/FileDataEntryBlob.jl
  src/DataBlobs/DataBlobs.jl
  src/DataBlobs/services/AbstractBlobEntries.jl
  src/DataBlobs/services/Blob.jl
  src/DataBlobs/services/BlobEntry.jl
  src/DataBlobs/services/BlobStores.jl
  src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
  src/DataBlobs/services/InMemoryStore.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGVariable.jl
  test/consol_DataEntryBlobTests.jl
  test/testBlocks.jl
Labels: bug fix, maintenance, standardization, data: entry=>blob

#986 fixes to Blob and BlobEntry helpers, entry.originId
  NEWS.md
  Project.toml
  attic/DataBlobs/FileDataEntryBlob.jl
  src/DataBlobs/services/BlobEntry.jl
  src/DataBlobs/services/BlobStores.jl
  src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
  src/Deprecated.jl
  test/consol_DataEntryBlobTests.jl
  test/iifInterfaceTests.jl
  test/testBlocks.jl
Labels: enhancement, refactor, data: entry=>blob

#987 release v0.20.1-rc1
  NEWS.md
  Project.toml
  attic/DataBlobs/FileDataEntryBlob.jl
  src/DataBlobs/services/BlobEntry.jl
  src/DataBlobs/services/BlobStores.jl
  src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
  src/Deprecated.jl
  test/consol_DataEntryBlobTests.jl
  test/iifInterfaceTests.jl
  test/testBlocks.jl
Labels: release

#996 new getBlobEntriesVariables
  src/DataBlobs/services/BlobEntry.jl
  src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
  src/DistributedFactorGraphs.jl
Labels: enhancement, feature request

#999 show progress when saveDFG
  src/FileDFG/services/FileDFG.jl
Labels: enhancement, FileDFG

#928 add dispatch on getPPE
  src/services/DFGVariable.jl
  test/testBlocks.jl
Labels: enhancement, API, PPE

#1001 v0.20.2-rc1
  Project.toml
  src/DataBlobs/entities/BlobEntry.jl
  src/DataBlobs/services/BlobEntry.jl
  src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/DFGVariable.jl
  test/testBlocks.jl
Labels: release

#997 Packed[Variable/Factor] as a DFGType and nstime as string
  docs/src/variable_factor_serialization.md
  src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/GraphsDFGSummaryTypes.jl
  test/data/0_21_0.tar.gz
  test/data/archive/0_20_0.tar.gz
Labels: breaking change, standardization

#998 Aligning blob with sdk
  Project.toml
  docs/extra/CoreAPI.fods
  src/DataBlobs/DataBlobs.jl
  src/DataBlobs/services/BlobEntry.jl
  src/DataBlobs/services/BlobStores.jl
  src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
  src/DistributedFactorGraphs.jl
  src/services/Serialization.jl
Labels: wip, standardization, data: entry=>blob, SDKs
