Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2023-09, with the labels that each got.

#1046 release v0.23.2-rc1
  .JuliaFormatter.toml
  .github/workflows/Formatter.yml
  .github/workflows/ci.yml
  Project.toml
  attic/DataBlobs/FileDataEntryBlob.jl
  attic/SerializationOld.jl
  attic/tests/testTranscodeTypeUnmarshaling.jl
  docs/make.jl
  ext/DFGPlots.jl
  src/Common.jl
  src/DataBlobs/entities/BlobEntry.jl
  src/DataBlobs/entities/BlobStores.jl
  src/DataBlobs/services/BlobEntry.jl
  src/DataBlobs/services/BlobPacking.jl
  src/DataBlobs/services/BlobStores.jl
  src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/GraphsDFG/FactorGraphs/BiMaps.jl
  src/GraphsDFG/FactorGraphs/FactorGraphs.jl
  src/GraphsDFG/GraphsDFG.jl
  src/GraphsDFG/entities/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFGSerialization.jl
  src/entities/AbstractDFG.jl
  src/entities/AbstractDFGSummary.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/CommonAccessors.jl
  src/services/CompareUtils.jl
  src/services/CustomPrinting.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/FactorGraphsTests.jl
  test/GraphsDFGSummaryTypes.jl
  test/compareTests.jl
  test/consol_DataEntryBlobTests.jl
  test/fileDFGTests.jl
  test/iifCompareTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/plottingTest.jl
  test/runtests.jl
  test/sandbox.jl
  test/solveTest.jl
  test/testBlocks.jl
  test/test_defVariable.jl
Labels: release

#1048 bug fix, getData with UUID
  Project.toml
  src/DataBlobs/services/BlobEntry.jl
  src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
  test/testBlocks.jl
Labels: testing, bug fix, data: entry=>blob

#1049 v0.23.3-rc1
  Project.toml
  src/DataBlobs/services/BlobEntry.jl
  src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
  test/testBlocks.jl
Labels: release

#1051 deleteBlobEntry! in PackedVariable and export getBlobEntryFirst
  src/DataBlobs/services/BlobEntry.jl
  src/DistributedFactorGraphs.jl
Labels: enhancement, bug fix
