Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2023-01, with the labels that each got.

#930 update compareFactor
  src/entities/DFGFactor.jl
  src/services/CompareUtils.jl
Labels: downstream, maintenance

#931 release v0.18.10-rc1
  .github/workflows/ci.yml
  Project.toml
  src/entities/DFGFactor.jl
  src/services/CompareUtils.jl
  src/services/DFGVariable.jl
Labels: release

#934 common dispatch for solveGraph! and Parametric
  src/Common.jl
Labels: enhancement, API, breaking change, standardization

#933 serialize DFGVariable top level JSON only
  Project.toml
  src/DataBlobs/entities/AbstractDataEntries.jl
  src/FileDFG/services/FileDFG.jl
  src/services/Serialization.jl
Labels: serialization, standardization

#926 simpler packVariable (API depr)
  src/Deprecated.jl
  src/services/Serialization.jl
Labels: enhancement, API, serialization, deprecation, possible breaking change

#936 Remove LightDFG and deprecate with error
  Project.toml
  README.md
  attic/DataStoreTests.jl
  docs/Project.toml
  docs/make.jl
  docs/src/BuildingGraphs.md
  docs/src/DrawingGraphs.md
  docs/src/GraphData.md
  docs/src/func_ref.md
  docs/src/variable_factor_serialization.md
  src/DFGPlots/DFGPlots.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/LightDFG/FactorGraphs/BiMaps.jl
  src/LightDFG/FactorGraphs/FactorGraphs.jl
  src/LightDFG/LightDFG.jl
  src/LightDFG/entities/LightDFG.jl
  src/LightDFG/services/LightDFG.jl
  src/services/AbstractDFG.jl
  test/LightDFGSummaryTypes.jl
  test/LightFactorGraphsTests.jl
  test/iifCompareTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/plottingTest.jl
  test/runtests.jl
  test/testBlocks.jl
Labels: breaking change, maintenance, standardization, deprecation

#940 rm depr pre-v0.19
  src/Deprecated.jl
Labels: deprecation

#944 release v0.19.1-rc1
  Project.toml
  src/services/Serialization.jl
Labels: release

#946 fix unpackFactor timezone cases
  Project.toml
  src/services/Serialization.jl
Labels: compat, serialization, bug fix

#947 release v0.19.2-rc1
  Project.toml
  src/services/Serialization.jl
Labels: release
