Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2023-08, with the labels that each got.

#1033 better data handling
  src/DataBlobs/services/BlobPacking.jl
  src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
Labels: enhancement, API, user experience, data: entry=>blob

#1035 add JuliaFormatter
  .JuliaFormatter.toml
  .github/workflows/Formatter.yml
Labels: enhancement, CI

#1036 another ls2 dispatch
  src/services/AbstractDFG.jl
Labels: enhancement, API

#1039 Fix mergeBlobEntries!
  src/DataBlobs/services/BlobEntry.jl
  src/DistributedFactorGraphs.jl
Labels: bug fix, data: entry=>blob

#1040 Run JuliaFormatter
  .JuliaFormatter.toml
  attic/DataBlobs/FileDataEntryBlob.jl
  attic/SerializationOld.jl
  attic/tests/testTranscodeTypeUnmarshaling.jl
  docs/make.jl
  ext/DFGPlots.jl
  src/Common.jl
  src/DataBlobs/entities/BlobEntry.jl
  src/DataBlobs/entities/BlobStores.jl
  src/DataBlobs/services/BlobEntry.jl
  src/DataBlobs/services/BlobPacking.jl
  src/DataBlobs/services/BlobStores.jl
  src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  src/FileDFG/services/FileDFG.jl
  src/GraphsDFG/FactorGraphs/BiMaps.jl
  src/GraphsDFG/FactorGraphs/FactorGraphs.jl
  src/GraphsDFG/GraphsDFG.jl
  src/GraphsDFG/entities/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFG.jl
  src/GraphsDFG/services/GraphsDFGSerialization.jl
  src/entities/AbstractDFG.jl
  src/entities/AbstractDFGSummary.jl
  src/entities/DFGFactor.jl
  src/entities/DFGVariable.jl
  src/services/AbstractDFG.jl
  src/services/CommonAccessors.jl
  src/services/CompareUtils.jl
  src/services/CustomPrinting.jl
  src/services/DFGFactor.jl
  src/services/DFGVariable.jl
  src/services/Serialization.jl
  test/FactorGraphsTests.jl
  test/GraphsDFGSummaryTypes.jl
  test/compareTests.jl
  test/consol_DataEntryBlobTests.jl
  test/fileDFGTests.jl
  test/iifCompareTests.jl
  test/iifInterfaceTests.jl
  test/interfaceTests.jl
  test/plottingTest.jl
  test/runtests.jl
  test/sandbox.jl
  test/solveTest.jl
  test/testBlocks.jl
  test/test_defVariable.jl
Labels: style, standardization

#1041 Fix ambiguities and test quality with Aqua
  Project.toml
  src/DataBlobs/services/BlobStores.jl
  src/Deprecated.jl
  src/DistributedFactorGraphs.jl
  test/runtests.jl
Labels: testing, maintenance, automation

#1042 fix tests for JL 1.10
  .github/workflows/ci.yml
  test/iifInterfaceTests.jl
Labels: testing, maintenance, julia version
