Repository JuliaRobotics/DistributedFactorGraphs.jl, pull requests merged in 2023-10, with the labels that each got.

#1052 getBiadjacencyMatrix: var and factor order input
  src/GraphsDFG/services/GraphsDFG.jl
Labels: enhancement, downstream

#1053 v0.23.4-rc1
  Project.toml
  src/DataBlobs/services/BlobEntry.jl
  src/DistributedFactorGraphs.jl
  src/GraphsDFG/services/GraphsDFG.jl
Labels: release

#1057 v0.23.5-rc1
  Project.toml
Labels: release

#1059 Optional show progress on copyGraph!
  src/services/AbstractDFG.jl
Labels: enhancement, performance, bug fix
